# Site settings
title: Gaurav Maharjan | Software Developer
description: Computer Science student at Virginia Tech focused on software engineering, cloud systems, and AI-driven applications.
baseurl: ""
url: "https://gmaharjan42.github.io"

# User settings
username: Gaurav Maharjan
user_description: Computer Science student at Virginia Tech with experience building AI-powered applications, cloud-based systems using Docker & Kubernetes, and full-stack software projects.
user_title: Computer Science Student | Software Developer

email: gmaharjan42@vt.edu
github_username: gmaharjan42
linkedin_username: gaurav-maharjan-906276328

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
